spring:
  application:
    name: load-balancer
server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      base-path: /
zuul:
  ignored-services: '*'
  sensitive-headers: # default value is Cookie, Set-Cookie, Authorization
  add-proxy-headers: true
  retryable: true
  prefix: /api
  strip-prefix: true
  routes:
    catalog: 
      path: /catalog/**
      service-id: catalog
    inventory:
      path: /inventory/**
      service-id: inventory