spring:
  application:
    name: load-balancer
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      base-path: /
zuul:
  sensitive-headers: # default value is Cookie, Set-Cookie, Authorization
  add-proxy-headers: false
  retryable: true
  #prefix: /api
  routes:
    catalog: 
      path: /catalog/**
      service-id: catalog